### ISSUE TITLE
acdh:hasAuthor values which point to an external URI such as http://viaf.org/viaf/251032539 should be parsed as names.

### ISSUE THREAD

**Issue by asilcetin** [acdh-oeaw/repo-gui#21]
Currently such values cannot be parsed and thus the author names for such resources are rendered empty. Until this feature is implemented, the hasAuthor property can only be seen in the expert-view on a single resource whereas the basic-view would show no author information.

**Comment by asilcetin** [comment]
See the VIAF Authority Cluster endpoint: https://www.oclc.org/developer/develop/web-services/viaf/authority-cluster.en.html

**Comment by asilcetin** [comment]
@csae8092's feedback: these authors are already in fedora and have such URIs as their identifiers. E.g. run the blazegraph query: Select * where { ?s ?p 'Andorfer'}

**Comment by nczirjak-acdh** [comment]
solved
