### ISSUE TITLE
Implement "cite this" widget supporting relevant citation formats

### ISSUE THREAD

**Issue by asilcetin** [acdh-oeaw/repo-gui#22]

**Comment by asilcetin** [comment]
Input from @bellerophons-pegasus regarding resource classes that can be cited: 
"Folgende Klassen sollten zitiert werden können: acdh:project, acdh:Collection, acdh:Resource, acdh:Publication. Eventuell auch acdh:Metadata; Bei acdh:Resource gibt es noch die Subklasse acdh:Image, die aber nicht zitiert werden muss, weil damit Logos und Titelbilder an Project, Collection oder Resource geknüpft werden."

**Comment by bellerophons-pegasus** [comment]
Please also consider the comment from redmine (issue 9184, 03.08.17): For the cite block: "AMA" can be removed. Instead "Chicago" could be added (http://www.citethisforme.com/citation-generator/chicago)

**Comment by nczirjak-acdh** [comment]
there is a bug:

https://fedora.hephaistos.arz.oeaw.ac.at/browser/oeaw_detail/aHR0cHM6Ly9mZWRvcmEuaGVwaGFpc3Rvcy5hcnoub2Vhdy5hYy5hdC9yZXN0L2RmLzY5L2JhL2JiL2RmNjliYWJiLWExNDMtNDk1Mi05Zjk5LTkyZDUyNDFkYzczYw==

Warning: Illegal string offset 'title' 
OeawFunctions->createCiteThisWidget() line 547

**Comment by nczirjak-acdh** [comment]
the copy button is not working :)

**Comment by nczirjak-acdh** [comment]
"there is a bug:

https://fedora.hephaistos.arz.oeaw.ac.at/browser/oeaw_detail/aHR0cHM6Ly9mZWRvcmEuaGVwaGFpc3Rvcy5hcnoub2Vhdy5hYy5hdC9yZXN0L2RmLzY5L2JhL2JiL2RmNjliYWJiLWExNDMtNDk1Mi05Zjk5LTkyZDUyNDFkYzczYw==

Warning: Illegal string offset 'title'
OeawFunctions->createCiteThisWidget() line 547"

This one is fixed

**Comment by bellerophons-pegasus** [comment]
First only implement MLA.

A complete citation for a **top level** collection, project in MLA looks like this:
Author. _Title_. Publisher, Year, URL (Handle, without http://). Accessed Day Month Year.
e. g.
Mörth, Karlheinz. _Dictionary Gate_. ACDH, 2013, hdl.handle.net/11022/0000-0000-001B-2. Accessed 12 Oct. 2017.

If there are two authors write:
[Last name of first author], [first name of first author] and [first name of second author] [last name of second author]
e.g.
Mörth, Karlheinz and Matej Durco

If there are three or more authors:
[Last name of first author], [first name of first author] et al.
e.g.
Mörth, Karlheinz et al.
 
-----
A complete citation for a **sub** collection and for resources (all things not having a Handle) in MLA looks like this:
Author. "Title". _Title of containing collection_, Publisher, Year, URL (Handle of top collection). Accessed Day Month (shortended to three letters) Year.
e.g.
Dallaji, Ines et al. "A Digital Dictionary of Tunis Arabic". _Dictionary Gate_. ACDH, 2013, hdl.handle.net/11022/0000-0000-001B-2. Accessed 12 Oct. 2017.

**Comment by bellerophons-pegasus** [comment]
Fields the information comes from:

- Title: hasTitle
- Publisher: hasHosting
- Handle URL: hasPid
- Title of containing collection: via isPartOf
- Year: year part from hasAvailableDate

For authors:

- first use hasAuthor
- if hasAuthor is empty use has Creator
- if hasAuthor and hasCreator are both set use both, but remove duplicates and first list the names in hasAuthor
- if hasAuthor and hasCreator are empty use hasContributor (but not its sub properties)
- if hasAuthor, hasCreator and hasContributer are empty leave the author information blank.

**Comment by asilcetin** [comment]
MLA for resources with types: acdh:project, acdh:Collection, acdh:Resource, acdh:Publication has been implemented with the specification above. Copy-button works as well.

Remaining features of this widget will be developed further under upcoming versions.
