### ISSUE TITLE
Extend the basic view with properties such as acdh:hasSchema, rdfs:seeAlso, acdh:hasLicense, acdh:has*Date, acdh:hasExtent (size), acdh:hasPid.

### ISSUE THREAD

**Issue by asilcetin** [acdh-oeaw/repo-gui#24]

**Comment by nczirjak-acdh** [comment]
done

**Comment by asilcetin** [comment]
With the decision of using hasAvailableDate as the main date of publication, I'm hiding the acdh:hasCreationStartDate and acdh:hasCreationEndDate from the basic view, since having more than one date on the basic view makes it too cluttered.

**Comment by nczirjak-acdh** [comment]
Please check the issue: 9184 

which says:  acdh:has*Date

They want to see every property which is a date. So i will put back the dates.
