### ISSUE TITLE
Latest Additions ordering

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/repo-gui#25]
Looks like "latest additions" are currently ordered by title; I'd say it's more intuitive to order them by date, meaning the latest added item comes first

**Comment by nczirjak-acdh** [comment]
ASC and DESC sorting is missing. And now the ordering is not okay in the front page.

Please fix it.

**Comment by asilcetin** [comment]
@nczirjak-acdh Thanks for the reminder, ASC/DESC has been added with [4d2f640](https://github.com/acdh-oeaw/repo-gui/commit/4d2f640bd516be8092764bf5fe47707540fc12c0) and the latest-addtions block should work correctly now :)
