### ISSUE TITLE
Simplify the date of publication filter to a listing of relevant years with (count)

### ISSUE THREAD

**Issue by asilcetin** [acdh-oeaw/repo-gui#39]

**Comment by asilcetin** [comment]
Like in the following example: https://www.narcis.nl/search/coll/publication/uquery/AUSTRIA/Language/en

**Comment by asilcetin** [comment]
To achieve this, the years can be listed in the same way we list types, with multiple selection possibility, like in the following mockup:
![year-of-pub-filter](https://user-images.githubusercontent.com/25176039/31773966-a52b1128-b4e4-11e7-86be-c6b24e23bc03.png)
However we may have to first discuss which query/url parameters are going to be used for this filter; we may want to keep the mindate/maxdate parameters for the "exact datepicker" and add a new parameter such as "years" which takes year numbers as a string in YYYY format with "+" delimiter.

**Comment by nczirjak-acdh** [comment]
Form and backend done, please extend the results.js in the theme

**Comment by nczirjak-acdh** [comment]
example: 
https://fedora.hephaistos.arz.oeaw.ac.at/browser/discover/type=Collection+or+Metadata+or+Person+or+Resource&years=2016+2015/titleasc/10/1
