### ISSUE TITLE
A search without any arguments should resolve/redirect into root results view, currently error page is shown.

### ISSUE THREAD

**Issue by asilcetin** [acdh-oeaw/repo-gui#43]

**Comment by asilcetin** [comment]
These events should show the root elements (or redirect to /browser/discover/root):
- Going to https://fedora.hephaistos.arz.oeaw.ac.at/browser/discover
- Clicking on the search icon on the front-page without typing anything
- Hitting Enter on the results view without anything selected or typed

I don't prefer to do this redirection on the client side with js, it would be an ugly solution, so please let's make it on the server side :)

**Comment by nczirjak-acdh** [comment]
Now if there is no metavalue then the default view is the root. But you still need to add some JS hack, because the url will not contains the root text and the limit or ordering.
